сервис статистики
LenaChaldina/java-explore-with-me pull request #3
Opened 2023-04-17 21:13 UTC by LenaChaldina

2023-04-18 16:40 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-04-18 16:40 UTC, ErkinKasymaliev commented on stats-service/stats-client/src/main/java/ru/practicum/Main.java
> +public class Main {
удалите этот класс

2023-04-18 16:40 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/mappers/StatsMapper.java
> +
удалите лишние проблемы

2023-04-18 16:40 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/repositorys/StatsRepository.java
> +    List<Stats> findAllBetweenDates(List<String> uris, LocalDateTime start, LocalDateTime end);
можно так findAllByUriInAndTimestampBetween(List<String> uris, LocalDateTime start, LocalDateTime end)

2023-04-18 16:40 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/controllers/StatsServerController.java
> +    public List<StatsUserDto> get(@RequestParam(name = "start") String start,
для дат можно использовать @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) и парсить в сервисе не надо

2023-04-19 12:51 UTC, LenaChaldina commented on stats-service/stats-client/src/main/java/ru/practicum/Main.java
> +public class Main {
done

2023-04-19 12:51 UTC, LenaChaldina commented on stats-service/stats-server/src/main/java/ru/practicum/stats/mappers/StatsMapper.java
> +
done

2023-04-19 13:02 UTC, LenaChaldina commented on stats-service/stats-server/src/main/java/ru/practicum/stats/repositorys/StatsRepository.java
> +    List<Stats> findAllBetweenDates(List<String> uris, LocalDateTime start, LocalDateTime end);
done

2023-04-19 13:56 UTC, LenaChaldina commented on stats-service/stats-server/src/main/java/ru/practicum/stats/controllers/StatsServerController.java
> +    public List<StatsUserDto> get(@RequestParam(name = "start") String start,
Да, так лучше! Только я кастомный паттерн добавила, чтобы считал нормально.

2023-04-19 14:28 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-04-24 12:27 UTC, merged